FROM continuumio/anaconda3

LABEL maintainer="Keid"

RUN conda update -n base conda \
  && conda create -n tf-env python=3.6 \
  && . activate tf-env \
  && conda install tensorflow \
  && conda clean --all

VOLUME /data

EXPOSE 8888

CMD jupyter notebook --notebook-dir=/data/notebooks --ip=0.0.0.0 --port=8888 --no-browser --allow-root
